from __future__ import annotations

from typing import Any

WORKFLOW_BINDING_CONTRACTS: dict[str, dict[str, Any]] = {
    'cwf_110': {
        'workflow_id': 'CWF-110',
        'workflow_name': 'cwf110_topic_discovery',
        'workflow_class': 'child',
        'parent_pack': 'WF-100',
        'primary_director': 'Narada',
        'supporting_directors': ['Chanakya', 'Chandra'],
        'governance_authority': [],
        'allowed_directors': ['Narada', 'Chanakya', 'Chandra'],
        'required_inputs': ['dossier_record', 'topic_intake_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_120': {
        'workflow_id': 'CWF-120',
        'workflow_name': 'cwf120_topic_qualification',
        'workflow_class': 'child',
        'parent_pack': 'WF-100',
        'primary_director': 'Chanakya',
        'supporting_directors': ['Krishna', 'Yama', 'Kubera'],
        'governance_authority': [],
        'allowed_directors': ['Chanakya', 'Krishna', 'Yama', 'Kubera'],
        'required_inputs': ['topic_candidate_board'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_130': {
        'workflow_id': 'CWF-130',
        'workflow_name': 'cwf130_topic_scoring',
        'workflow_class': 'child',
        'parent_pack': 'WF-100',
        'primary_director': 'Krishna',
        'supporting_directors': ['Narada', 'Chanakya', 'Chandra'],
        'governance_authority': [],
        'allowed_directors': ['Krishna', 'Narada', 'Chanakya', 'Chandra'],
        'required_inputs': ['topic_finalization_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_140': {
        'workflow_id': 'CWF-140',
        'workflow_name': 'cwf140_research_synthesis',
        'workflow_class': 'child',
        'parent_pack': 'WF-100',
        'primary_director': 'Vyasa',
        'supporting_directors': ['Saraswati', 'Durga', 'Krishna'],
        'governance_authority': [],
        'allowed_directors': ['Vyasa', 'Saraswati', 'Durga', 'Krishna'],
        'required_inputs': ['topic_finalization_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_210': {
        'workflow_id': 'CWF-210',
        'workflow_name': 'cwf210_script_generation',
        'workflow_class': 'child',
        'parent_pack': 'WF-200',
        'primary_director': 'Vyasa',
        'supporting_directors': ['Saraswati', 'Krishna'],
        'governance_authority': [],
        'allowed_directors': ['Vyasa', 'Saraswati', 'Krishna'],
        'required_inputs': ['topic_finalization_packet', 'research_synthesis_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_220': {
        'workflow_id': 'CWF-220',
        'workflow_name': 'cwf220_script_debate',
        'workflow_class': 'child',
        'parent_pack': 'WF-200',
        'primary_director': 'Krishna',
        'supporting_directors': ['Durga', 'Yama', 'Saraswati'],
        'governance_authority': [],
        'allowed_directors': ['Krishna', 'Durga', 'Yama', 'Saraswati'],
        'required_inputs': ['script_draft_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_230': {
        'workflow_id': 'CWF-230',
        'workflow_name': 'cwf230_script_refinement',
        'workflow_class': 'child',
        'parent_pack': 'WF-200',
        'primary_director': 'Saraswati',
        'supporting_directors': ['Krishna', 'Vyasa'],
        'governance_authority': [],
        'allowed_directors': ['Saraswati', 'Krishna', 'Vyasa'],
        'required_inputs': ['script_debate_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_240': {
        'workflow_id': 'CWF-240',
        'workflow_name': 'cwf240_final_script_shaping',
        'workflow_class': 'child',
        'parent_pack': 'WF-200',
        'primary_director': 'Krishna',
        'supporting_directors': ['Saraswati', 'Durga'],
        'governance_authority': [],
        'allowed_directors': ['Krishna', 'Saraswati', 'Durga'],
        'required_inputs': ['script_refinement_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_310': {
        'workflow_id': 'CWF-310',
        'workflow_name': 'cwf310_execution_context_builder',
        'workflow_class': 'child',
        'parent_pack': 'WF-300',
        'primary_director': 'Krishna',
        'supporting_directors': ['Durga'],
        'governance_authority': [],
        'allowed_directors': ['Krishna', 'Durga'],
        'required_inputs': ['final_script_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_320': {
        'workflow_id': 'CWF-320',
        'workflow_name': 'cwf320_platform_packager',
        'workflow_class': 'child',
        'parent_pack': 'WF-300',
        'primary_director': 'Saraswati',
        'supporting_directors': ['Krishna'],
        'governance_authority': [],
        'allowed_directors': ['Saraswati', 'Krishna'],
        'required_inputs': ['execution_context_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_330': {
        'workflow_id': 'CWF-330',
        'workflow_name': 'cwf330_asset_brief_generator',
        'workflow_class': 'child',
        'parent_pack': 'WF-300',
        'primary_director': 'Durga',
        'supporting_directors': ['Saraswati'],
        'governance_authority': [],
        'allowed_directors': ['Durga', 'Saraswati'],
        'required_inputs': ['platform_package_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_340': {
        'workflow_id': 'CWF-340',
        'workflow_name': 'cwf340_lineage_validator',
        'workflow_class': 'child',
        'parent_pack': 'WF-300',
        'primary_director': 'Krishna',
        'supporting_directors': ['Yama', 'Kubera'],
        'governance_authority': [],
        'allowed_directors': ['Krishna', 'Yama', 'Kubera'],
        'required_inputs': ['asset_brief_packet', 'execution_context_packet', 'platform_package_packet', 'final_script_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_410': {
        'workflow_id': 'CWF-410',
        'workflow_name': 'cwf410_thumbnail_generator',
        'workflow_class': 'child',
        'parent_pack': 'WF-400',
        'primary_director': 'Durga',
        'supporting_directors': ['Saraswati'],
        'governance_authority': [],
        'allowed_directors': ['Durga', 'Saraswati'],
        'required_inputs': ['context_engineering_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_420': {
        'workflow_id': 'CWF-420',
        'workflow_name': 'cwf420_visual_asset_planner',
        'workflow_class': 'child',
        'parent_pack': 'WF-400',
        'primary_director': 'Durga',
        'supporting_directors': ['Krishna'],
        'governance_authority': [],
        'allowed_directors': ['Durga', 'Krishna'],
        'required_inputs': ['thumbnail_concept_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_430': {
        'workflow_id': 'CWF-430',
        'workflow_name': 'cwf430_audio_script_optimizer',
        'workflow_class': 'child',
        'parent_pack': 'WF-400',
        'primary_director': 'Saraswati',
        'supporting_directors': ['Durga'],
        'governance_authority': [],
        'allowed_directors': ['Saraswati', 'Durga'],
        'required_inputs': ['visual_asset_plan_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_440': {
        'workflow_id': 'CWF-440',
        'workflow_name': 'cwf440_media_package_finalizer',
        'workflow_class': 'child',
        'parent_pack': 'WF-400',
        'primary_director': 'Krishna',
        'supporting_directors': ['Durga', 'Saraswati'],
        'governance_authority': [],
        'allowed_directors': ['Krishna', 'Durga', 'Saraswati'],
        'required_inputs': ['audio_optimized_script_packet', 'visual_asset_plan_packet', 'thumbnail_concept_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_510': {
        'workflow_id': 'CWF-510',
        'workflow_name': 'cwf510_platform_metadata_generator',
        'workflow_class': 'child',
        'parent_pack': 'WF-500',
        'primary_director': 'Chanakya',
        'supporting_directors': ['Krishna', 'Saraswati'],
        'governance_authority': [],
        'allowed_directors': ['Chanakya', 'Krishna', 'Saraswati'],
        'required_inputs': ['media_production_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_520': {
        'workflow_id': 'CWF-520',
        'workflow_name': 'cwf520_distribution_planner',
        'workflow_class': 'child',
        'parent_pack': 'WF-500',
        'primary_director': 'Krishna',
        'supporting_directors': ['Chanakya'],
        'governance_authority': [],
        'allowed_directors': ['Krishna', 'Chanakya'],
        'required_inputs': ['platform_metadata_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_530': {
        'workflow_id': 'CWF-530',
        'workflow_name': 'cwf530_publish_readiness_checker',
        'workflow_class': 'child',
        'parent_pack': 'WF-500',
        'primary_director': 'Yama',
        'supporting_directors': ['Krishna'],
        'governance_authority': [],
        'allowed_directors': ['Yama', 'Krishna'],
        'required_inputs': ['distribution_plan_packet', 'platform_metadata_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': True,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_610': {
        'workflow_id': 'CWF-610',
        'workflow_name': 'performance_metrics_collector',
        'workflow_class': 'child_workflow',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': [],
        'allowed_directors': ['Krishna'],
        'required_inputs': [],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_620': {
        'workflow_id': 'CWF-620',
        'workflow_name': 'audience_feedback_aggregator',
        'workflow_class': 'child_workflow',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': [],
        'allowed_directors': ['Krishna'],
        'required_inputs': [],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'cwf_630': {
        'workflow_id': 'CWF-630',
        'workflow_name': 'evolution_signal_synthesizer',
        'workflow_class': 'child_workflow',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': [],
        'allowed_directors': ['Krishna'],
        'required_inputs': [],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'wf_000': {
        'workflow_id': 'WF-000',
        'workflow_name': 'wf000_health_check',
        'workflow_class': 'system',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': [],
        'allowed_directors': ['Krishna'],
        'required_inputs': ['health_probe_request'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'high',
        },
    },
    'wf_001': {
        'workflow_id': 'WF-001',
        'workflow_name': 'wf001_dossier_create',
        'workflow_class': 'parent',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': [],
        'allowed_directors': ['Krishna'],
        'required_inputs': ['intake_packet'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'wf_010': {
        'workflow_id': 'WF-010',
        'workflow_name': 'wf010_parent_orchestrator',
        'workflow_class': 'parent',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': [],
        'allowed_directors': ['Krishna'],
        'required_inputs': ['dossier_record', 'route_signal'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST', 'ROUTE_PHASE1_REPLAY'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'wf_020': {
        'workflow_id': 'WF-020',
        'workflow_name': 'wf020_final_approval',
        'workflow_class': 'governance',
        'parent_pack': '',
        'primary_director': 'Yama',
        'supporting_directors': [],
        'governance_authority': ['Krishna'],
        'allowed_directors': ['Yama', 'Krishna'],
        'required_inputs': ['final_script_packet', 'media_production_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': True,
            'escalate_to': 'WF-900',
            'severity': 'high',
        },
    },
    'wf_021': {
        'workflow_id': 'WF-021',
        'workflow_name': 'wf021_replay_remodify',
        'workflow_class': 'governance',
        'parent_pack': '',
        'primary_director': 'Yama',
        'supporting_directors': ['Krishna', 'Vyasa'],
        'governance_authority': [],
        'allowed_directors': ['Yama', 'Krishna', 'Vyasa'],
        'required_inputs': ['rejection_packet', 'replay_context'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'high',
        },
    },
    'wf_022': {
        'workflow_id': 'WF-022',
        'workflow_name': 'wf022_provider_packet_bridge',
        'workflow_class': 'system_bridge',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': ['Yama', 'Kubera'],
        'allowed_directors': ['Krishna', 'Yama', 'Kubera'],
        'required_inputs': ['approved_packet', 'provider_target'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'high',
        },
    },
    'wf_023': {
        'workflow_id': 'WF-023',
        'workflow_name': 'wf023_downstream_resource_preparation',
        'workflow_class': 'planning',
        'parent_pack': '',
        'primary_director': 'Aruna',
        'supporting_directors': [],
        'governance_authority': ['Krishna'],
        'allowed_directors': ['Aruna', 'Krishna'],
        'required_inputs': ['final_script_packet', 'context_engineering_packet'],
        'route_bindings': [],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'normal',
        },
    },
    'wf_100': {
        'workflow_id': 'WF-100',
        'workflow_name': 'wf100_topic_intelligence_pack',
        'workflow_class': 'parent_pack',
        'parent_pack': '',
        'primary_director': 'Narada',
        'supporting_directors': [],
        'governance_authority': ['Yama', 'Kubera'],
        'allowed_directors': ['Narada', 'Yama', 'Kubera'],
        'required_inputs': ['dossier_record', 'orchestration_decision'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'medium',
        },
    },
    'wf_200': {
        'workflow_id': 'WF-200',
        'workflow_name': 'wf200_script_intelligence_pack',
        'workflow_class': 'parent_pack',
        'parent_pack': '',
        'primary_director': 'Vyasa',
        'supporting_directors': [],
        'governance_authority': ['Yama', 'Kubera'],
        'allowed_directors': ['Vyasa', 'Yama', 'Kubera'],
        'required_inputs': ['topic_finalization_packet', 'research_synthesis_packet', 'orchestration_decision'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'medium',
        },
    },
    'wf_300': {
        'workflow_id': 'WF-300',
        'workflow_name': 'wf300_context_engineering_pack',
        'workflow_class': 'parent_pack',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': ['Yama', 'Kubera'],
        'allowed_directors': ['Krishna', 'Yama', 'Kubera'],
        'required_inputs': ['final_script_packet'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'medium',
        },
    },
    'wf_400': {
        'workflow_id': 'WF-400',
        'workflow_name': 'wf400_media_production_pack',
        'workflow_class': 'parent_pack',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': ['Durga', 'Saraswati'],
        'allowed_directors': ['Krishna', 'Durga', 'Saraswati'],
        'required_inputs': ['context_engineering_packet'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'medium',
        },
    },
    'wf_500': {
        'workflow_id': 'WF-500',
        'workflow_name': 'wf500_publishing_distribution_pack',
        'workflow_class': 'parent_pack',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': ['Yama', 'Krishna'],
        'allowed_directors': ['Krishna', 'Yama'],
        'required_inputs': ['media_production_packet'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_FAST'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': True,
            'escalate_to': 'WF-900',
            'severity': 'medium',
        },
    },
    'wf_600': {
        'workflow_id': 'WF-600',
        'workflow_name': 'wf600_analytics_evolution_pack',
        'workflow_class': 'parent_pack',
        'parent_pack': '',
        'primary_director': 'Chandra',
        'supporting_directors': [],
        'governance_authority': ['Chitragupta', 'Yama'],
        'allowed_directors': ['Chandra', 'Chitragupta', 'Yama'],
        'required_inputs': ['publish_ready_packet', 'runtime_context'],
        'route_bindings': ['ROUTE_PHASE1_STANDARD', 'ROUTE_PHASE1_ANALYTICS'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': False,
            'escalate_to': 'WF-900',
            'severity': 'medium',
        },
    },
    'wf_900': {
        'workflow_id': 'WF-900',
        'workflow_name': 'wf900_error_handler',
        'workflow_class': 'system',
        'parent_pack': '',
        'primary_director': 'Krishna',
        'supporting_directors': [],
        'governance_authority': [],
        'allowed_directors': ['Krishna'],
        'required_inputs': ['error_event'],
        'route_bindings': ['ROUTE_PHASE1_REPLAY'],
        'gate_rules': {
            'enforce_director_binding': True,
            'require_dossier_id': True,
            'require_declared_inputs': True,
            'require_governance_ack_on_release': True,
            'escalate_to': 'WF-900',
            'severity': 'high',
        },
    },
}

def get_workflow_contract(workflow_slug: str) -> dict[str, Any]:
    key = workflow_slug.lower().replace("-", "_")
    return WORKFLOW_BINDING_CONTRACTS.get(
        key,
        {
            "workflow_id": workflow_slug.upper().replace("_", "-"),
            "workflow_name": workflow_slug,
            "workflow_class": "unknown",
            "parent_pack": "",
            "primary_director": "Krishna",
            "supporting_directors": [],
            "governance_authority": [],
            "allowed_directors": ["Krishna"],
            "required_inputs": [],
            "route_bindings": [],
            "gate_rules": {
                "enforce_director_binding": True,
                "require_dossier_id": True,
                "require_declared_inputs": False,
                "require_governance_ack_on_release": False,
                "escalate_to": "WF-900",
                "severity": "normal",
            },
        },
    )
